### ISSUE TITLE
CRC check failing for every telegram

### ISSUE THREAD

**Issue by pro-sumer** [reneklootwijk/node-dsmr#10]
An older version of `node-dsrm` has been working fine for me for months. Today I updated to Node.js 14 (LTS) and updated all Node.js modules installed on my Raspberry Pi (I use this to get P1 data into my Homey via [Homey p1 smartmeter DSMR reader](https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader)).

Now I get a CRC check failure for every telegram:

```
{"message":"Telegram is not processed because of corruption (59ae/b9bc)","level":"error"}
```

As a workaround I added `disableCrcChecking: true` when initialising `dsmr`; P1 data are transferred fine then.

However, it would be nicer if the CRC check worked. What's wrong with my setup?

**Comment by reneklootwijk** [comment]
The CRC check has been added in the latest version. Are you sure the telegrams you receive are not corrupted, meaning one or more characters are not correct?

My experience is that a Raspberry 1 and 2 have difficulties processing telegrams of a DSMR5 meter which sends a telegram each second. The result is that one or more characters in the telegram are wrong causing a wrong CRC calculation.

**Comment by pro-sumer** [comment]
I'm using a Raspberry Pi Zero W with a DSMR5 meter (with an update every second), so you might be right!

How can I check whether one or more characters are wrong?

**Comment by reneklootwijk** [comment]
Can you post a telegram that results in  a CRC error?

**Comment by reneklootwijk** [comment]
You can try cat /dev/<USB port>, e.g. cat /dev/ttyUSB0.

**Comment by pro-sumer** [comment]
I currently can't reproduce this issue.

Maybe the P1 script needs to run for a long(er) time to reproduce it?

Will keep an eye on this.

**Comment by pro-sumer** [comment]
Issue started again about 6 hours ago.

This is a single telegram (redacted):
```
/Ene5\XS210 ESMR 5.0

1-3:0.2.8(<value>)
0-0:1.0.0(<value>W)
0-0:96.1.1(<value>)
1-0:1.8.1(<value>*kWh)
1-0:1.8.2(<value>*kWh)
1-0:2.8.1(<value>*kWh)
1-0:2.8.2(<value>*kWh)
0-0:96.14.0(<value>)
1-0:1.7.0(<value>*kW)
1-0:2.7.0(<value>*kW)
0-0:96.7.21(<value>)
0-0:96.7.9(<value>)
1-0:99.97.0(0)(0-0:96.7.19)
1-0:32.32.0(<value>)
1-0:32.36.0(<value>)
0-0:96.13.0()
1-0:32.7.0(<value>*V)
1-0:31.7.0(<value>*A)
1-0:21.7.0(<value>*kW)
1-0:22.7.0(<value>*kW)
0-1:24.1.0(<value>)
0-1:96.1.0(<value>)
0-1:24.2.1(<value>W)(<value>*m3)
!<value>
```

Is there some kind of check I can do for you without posting my actual numbers here?

**Comment by reneklootwijk** [comment]
This looks indeed ok. What I see when I receive a malformed telegram is missing characters or ',' instead of '.', that get of things. To do the calculation I like to see the complete telegram. If you do mind to publish it here, do you mind to mail it me?

**Comment by pro-sumer** [comment]
I have tested [your CRC check implementation](https://github.com/reneklootwijk/node-dsmr/blob/master/lib/crc.js) on several telegrams from `/dev/ttyUSB0` and the calculated checksum always matches the expected/reported one...

So my challenge is going to be capturing a malformed telegram? How can I do that?

**Comment by reneklootwijk** [comment]
Did you capture the telegrams directly from the serial port or does the code now reports the checksum is correct? What exactly did you do?

**Comment by pro-sumer** [comment]
I wrote as few code as possible:
* (each time) manually copy contents of 1 telegram from `cat /dev/ttyUSB0` to a text file `telegram.txt`
* read that file and use your `crc` function to display the calculated CRC
* used a calculator (...) to compare the expected hexadecimal CRC with the calculated decimal CRC

```
fs.readFile('telegram.txt', 'utf8', (error, data) => {
  console.log(crc(data.toString().split(/\r?\n/)))
})
```

For each telegram I tested this way the expected and calculated CRC's did match.

**Comment by reneklootwijk** [comment]
I think I found the issue, but did not solve it yet. It has to do with the delimiter of the readline parser in the serialport module. Will be continued..

**Comment by reneklootwijk** [comment]
The issue has been fixed in version 0.1.20. Are you able to test it?

**Comment by pro-sumer** [comment]
After executing `npm install node-dsmr@0.1.20`, removing `disableCrcChecking: true`, and restarting the P1 script I get one error:

```
{"message":"Telegram is not processed because of corruption (xxxx/yyyy)","level":"error"}
```

After that I do get real-time updates in the Homey P1 App though (without further errors).

However, with the old version I did not got any CRC errors (at all) until the script was running several hours, so I will check again at a later time.

**Comment by pro-sumer** [comment]
I had one more error this morning around 0:00 when the Pi restarted the P1 script as scheduled (because of a Node.js memory leak).

No other errors though, so I think you solved this! Thanks!
