### ISSUE TITLE
Incoherent results in consumed/produced vars

### ISSUE THREAD

**Issue by rkokkelk** [reneklootwijk/node-dsmr#19]
first of all, thanks for this nice module. Its being used by an app which I in turn use for Home automation using [Homey](https://homey.app/nl-nl/app/com.p1/P1-Slimme-meter/). Using this app I noticed that my actual usage was shown as produced electricity instead of consumed electricity. Currently, I've got no electricity producing devices.

Delving into the app I concluded that the problem was your node-dsrm parser which labels the electricity incorrectly. As can be seen below, `actualConsumed` shows my current usage correctly, however, the usage per `L*` shows the usage in `instantaneousProducedElectricityL*` instead of `instantaneousConsumedElectricityL*`.

Any help fixing this is highly appreciated.

```js
{ equipmentId: 'E00XXXXXXXXXX121',
  totalConsumed1: 849.545,
  totalConsumed2: 972.065,
  totalProduced1: 0,
  totalProduced2: 0,
  activeTariff: 2,
  actualConsumed: 0.444,
  actualProduced: 0,
  failures: 7,
  failuresLong: 2,
  failureLog: [],
  voltageSagsL1: 0,
  voltageSagsL2: 0,
  voltageSagsL3: 0,
  voltageSwellsL1: 1,
  voltageSwellsL2: 1,
  voltageSwellsL3: 1,
  instantaneousVoltageL1: 239.9,
  instantaneousVoltageL2: 239.1,
  instantaneousVoltageL3: 241.3,
  instantaneousCurrentL1: 1,
  instantaneousCurrentL2: 0,
  instantaneousCurrentL3: 1,
  instantaneousProducedElectricityL1: 0.234,
  instantaneousProducedElectricityL2: 0,
  instantaneousProducedElectricityL3: 0.209,
  instantaneousConsumedElectricityL1: 0,
  instantaneousConsumedElectricityL2: 0,
  instantaneousConsumedElectricityL3: 0 }
```

**Comment by reneklootwijk** [comment]
This was fixed in version 0.1.13 more than 1 year ago.
