### ISSUE TITLE
strange characters

### ISSUE THREAD

**Issue by Itsmmai** [reneklootwijk/node-dsmr#21]
Hi,

When using node-dsr on a dutch electricity meter from 2011 I receive strange characters 

{"message":"Unknown id: 0-0:96.�.�(�B����3�303035303�3�3�3�3�3�3�3���","level":"debug"}
{"message":"Unknown id: �-0:�.�.�(���35.�63���詍","level":"debug"}
{"message":"Unknown id: �-0:�.�.�(��9��.099���詍","level":"debug"}
{"message":"Unknown id: �-0:�.�.�(03�65.093���詍","level":"debug"}
{"message":"Unknown id: �-0:�.�.�(0�33�.�95���詍","level":"debug"}
{"message":"Unknown id: 0-0:96.��.0(000���","level":"debug"}
{"message":"Unknown id: �-0:�.�.0(0000.30��ש�","level":"debug"}
{"message":"Unknown id: �-0:�.�.0(0000.00��ש�","level":"debug"}
{"message":"Unknown id: 0-0:��.0.0(0999.00��ש�","level":"debug"}
{"message":"Unknown id: 0-0:96.3.�0(���","level":"debug"}
{"message":"Unknown id: 0-0:96.�3.�(��","level":"debug"}
{"message":"Unknown id: 0-0:96.�3.0(��","level":"debug"}
{"message":"Unknown id: 0-�:��.�.0(3��","level":"debug"}
{"message":"Unknown id: 0-�:96.�.0(3�3�3�303�353�3�3�303039303�3�3�3���","level":"debug"}
{"message":"Unknown id: 0-�:��.3.0(��������0000�(00�(60�(��(0-�:��.�.��(�3��","level":"debug"}
{"message":"Unknown id: 0-�:��.�.0(���","level":"debug"}
{"message":"SmartMeter: Telegram {\"power\":{},\"gas\":{}}","level":"debug"}
{"message":"p1 smartmeter update gas or power","level":"info"}

I'm using an old smartmeter, not sure what version (I think 2.x).

My settings are:

const usbPort = '/dev/ttyUSB0'
const bps = 9600
const bits = 7
const parity = 'none' (even is doing nothing)
const disableCrcChecking = 'true'

When I use a separate program called GTKTERM I've to use the following settings:

/dev/ttyUSB0, 9600, 7, E, 1

and then I receive normal data:

<img width="647" alt="Schermafbeelding 2021-11-17 om 18 53 38" src="https://user-images.githubusercontent.com/24639986/142255487-574af19e-441b-4ced-89ec-8519bef73424.png">

Can you help me out ?
Thanks in advance!

Abel

**Comment by reneklootwijk** [comment]
Can you show the code where you instantiate the SmartMeter class?

**Comment by Itsmmai** [comment]
Eeeeeh. Geen idee. No clue
________________________________
Van: Rene Klootwijk ***@***.***>
Verzonden: Wednesday, November 17, 2021 7:34:19 PM
Aan: reneklootwijk/node-dsmr ***@***.***>
CC: Ab Helversteijn-Smit ***@***.***>; Author ***@***.***>
Onderwerp: Re: [reneklootwijk/node-dsmr] strange characters (Issue #21)


Can you show the code where you instantiate the SmartMeter class?

**Comment by reneklootwijk** [comment]
The node-dsmr module by itself does nothing, you have to initialize it. How do you do this?

**Comment by Itsmmai** [comment]
Check. I’m using the app for my Homey

https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader


________________________________
Van: Rene Klootwijk ***@***.***>
Verzonden: Wednesday, November 17, 2021 7:34:19 PM
Aan: reneklootwijk/node-dsmr ***@***.***>
CC: Ab Helversteijn-Smit ***@***.***>; Author ***@***.***>
Onderwerp: Re: [reneklootwijk/node-dsmr] strange characters (Issue #21)


Can you show the code where you instantiate the SmartMeter class?

**Comment by reneklootwijk** [comment]
There is a bug in that app. In the p1.js file the SmartMeter class is instantiated using:

```
const p1Meter = new dsmr({ 
    port: usbPort,  
    baudrate: bps,  
    bits: bits,  
    parity: parity,  
})
```

bits: bits, should be databits: bits.

I do not maintain that code so you need to raise the issue at the owner of that code.

**Comment by Itsmmai** [comment]
You are the best !!! thank you very much !!

Van: Rene Klootwijk ***@***.***>
Datum: woensdag, 17 november 2021 om 19:50
Aan: reneklootwijk/node-dsmr ***@***.***>
CC: Ab Helversteijn-Smit ***@***.***>, Author ***@***.***>
Onderwerp: Re: [reneklootwijk/node-dsmr] strange characters (Issue #21)

There is a bug in that app. In the p1.js file the SmartMeter class is instantiated using:

const p1Meter = new dsmr({ port: usbPort, baudrate: bps, bits: bits, parity: parity, })
bits: bits, should be databits: bits.

I do not maintain that code so you need to raise the issue at the owner of that code.
