### ISSUE TITLE
issue with gas data

### ISSUE THREAD

**Issue by Henkkas52** [reneklootwijk/node-dsmr#30]
I have an issue with gas data, I can't figure out why.

Telegram looks like this:
![afbeelding](https://user-images.githubusercontent.com/80907008/216831646-a33e8e8f-943e-4ae8-8a0c-1b427da16da6.png)

As you can see, gas valve is open and gas volume is there.
But if I look at the parser data I see this:

![afbeelding](https://user-images.githubusercontent.com/80907008/216831747-1a5e4692-e24e-45bf-b593-eb5217a23fa0.png)

As you can see, only the valve-position is there, but not "consumed" ????

**Comment by reneklootwijk** [comment]
Can you post the telegram in text form not as picture, that will make it easier to test?

**Comment by Henkkas52** [comment]
/FLU5\253770234_A



0-0:96.1.4(50217)

0-0:96.1.1(3153414731313030343339383534)

0-0:1.0.0(230205174141W)

1-0:1.8.1(002017.966*kWh)

1-0:1.8.2(002556.895*kWh)

1-0:2.8.1(001862.477*kWh)

1-0:2.8.2(000800.504*kWh)

0-0:96.14.0(0002)

1-0:1.4.0(00.191*kW)

1-0:1.6.0(230202010000W)(02.125*kW)

0-0:98.1.0(2)(1-0:1.6.0)(1-0:1.6.0)(230101000000W)(221201173000W)(04.350*kW)(230201000000W)(230101180000W)(02.625*kW)

1-0:1.7.0(00.252*kW)

1-0:2.7.0(00.000*kW)

1-0:21.7.0(00.252*kW)

1-0:22.7.0(00.000*kW)

1-0:32.7.0(229.6*V)

1-0:31.7.0(001.47*A)

0-0:96.3.10(1)

0-0:17.0.0(999.9*kW)

1-0:31.4.0(999*A)

0-0:96.13.0()

0-1:24.1.0(003)

0-1:96.1.1(37464C4F32313231313539393130)

0-1:24.4.0(1)

0-1:24.2.3(230205174004W)(02030.186*m3)

!837D

**Comment by reneklootwijk** [comment]
I had a better look, you seem to be using an older version of the module that did not support the Belgian telegram format. When I run the telegram through the parser of the current version I get the following output:

```
{
    "electricity": {
        "totalConsumed1": 2017.966,
        "totalConsumed2": 2556.895,
        "totalProduced1": 1862.477,
        "totalProduced2": 800.504,
        "activeTariff": 2,
        "capacity": {
            "import": {
                "avgDemand": 0.191,
                "runningMonth": {
                    "maxDemand": 2.125,
                    "timestamp": 1675296000
                },
                "history": [
                    {
                        "start": 1672527600,
                        "end": 1669912200,
                        "maxDemand": 4.35
                    },
                    {
                        "start": 1675206000,
                        "end": 1672592400,
                        "maxDemand": 2.625
                    }
                ]
            }
        },
        "actualConsumed": 0.252,
        "actualProduced": 0,
        "instantaneousConsumedPowerL1": 0.252,
        "instantaneousProducedPowerL1": 0,
        "instantaneousVoltageL1": 229.6,
        "instantaneousCurrentL1": 1.47,
        "switchPosition": 1,
        "thresholdkW": 999.9,
        "equipmentId": "1SAG1100439854"
    },
    "gas": {
        "timestamp": 1675615204,
        "totalConsumed": 2030.186,
        "equipmentId": "7FLO2121159910",
        "valvePosition": 1
    },
    "water": {},
    "meterModel": "FLU5\\253770234_A",
    "dsmrVersion": 5.0217,
    "timestamp": 1675615301,
    "messages": {
        "text": ""
    },
    "connectedMeters": [
        {
            "mbusId": "1",
            "type": 3,
            "description": "Gas meter"
        }
    ]
}
```

**Comment by Henkkas52** [comment]
Today I updated node-dsmr.
I used `npm update node-dsmr` in the folder /.node-red. 

It said I have the latest version.

**Comment by reneklootwijk** [comment]
Can you look at the version specified in the package.json file? Pretty sure it is version 1.x.

**Comment by reneklootwijk** [comment]
Maybe node-red still requires version 1.x. Version 2 introduced some breaking changes so the node-red integration code needs to be modified probably.

**Comment by Henkkas52** [comment]
indeed, I have 1.0.2.

**Comment by Henkkas52** [comment]
What do I have to do to integrate v2.xx into the system. By the way, I only use the parser!

**Comment by reneklootwijk** [comment]
I do not know how node-red integrated this module. The breaking changes are described on the README.md.
