### ISSUE TITLE
Timestamps of capacity runningMonth and history is fixed value

### ISSUE THREAD

**Issue by Henkkas52** [reneklootwijk/node-dsmr#31]
I found that timestamp of capacity.runningMonth and also in history 'start/end' items are fixed values rather then values taken from telegram.
I send you this telegram.

/FLU5\253769484_A

0-0:96.1.4(50217)

0-0:96.1.1(3153414733313030313835353436)

0-0:1.0.0(230206102154W)

1-0:1.8.1(002110.548*kWh)

1-0:1.8.2(003326.981*kWh)

1-0:2.8.1(008416.436*kWh)

1-0:2.8.2(003384.335*kWh)

0-0:96.14.0(0001)

1-0:1.4.0(00.000*kW)

1-0:1.6.0(230201170000W)(02.401*kW)

0-0:98.1.0(2)(1-0:1.6.0)(1-0:1.6.0)(230101000000W)(221202164500W)(02.772*kW)(230201000000W)(230125170000W)(02.600*kW)

1-0:1.7.0(00.000*kW)

1-0:2.7.0(00.902*kW)

1-0:21.7.0(00.108*kW)

1-0:41.7.0(00.000*kW)

1-0:61.7.0(00.000*kW)

1-0:22.7.0(00.000*kW)

1-0:42.7.0(00.376*kW)

1-0:62.7.0(00.634*kW)

1-0:32.7.0(233.1*V)

1-0:52.7.0(231.8*V)

1-0:72.7.0(235.2*V)

1-0:31.7.0(000.76*A)

1-0:51.7.0(001.78*A)

1-0:71.7.0(003.03*A)

0-0:96.3.10(1)

0-0:17.0.0(999.9*kW)

1-0:31.4.0(999*A)

0-0:96.13.0()

!3617

**Comment by reneklootwijk** [comment]
This is the output of the parser:

```
{
    "electricity": {
        "totalConsumed1": 2110.548,
        "totalConsumed2": 3326.981,
        "totalProduced1": 8416.436,
        "totalProduced2": 3384.335,
        "activeTariff": 1,
        "capacity": {
            "import": {
                "avgDemand": 0,
                "runningMonth": {
                    "maxDemand": 2.401,
                    "timestamp": 1675267200
                },
                "history": [
                    {
                        "start": 1672527600,
                        "end": 1669995900,
                        "maxDemand": 2.772
                    },
                    {
                        "start": 1675206000,
                        "end": 1674662400,
                        "maxDemand": 2.6
                    }
                ]
            }
        },
        "actualConsumed": 0,
        "actualProduced": 0.902,
        "instantaneousConsumedPowerL1": 0.108,
        "instantaneousConsumedPowerL2": 0,
        "instantaneousConsumedPowerL3": 0,
        "instantaneousProducedPowerL1": 0,
        "instantaneousProducedPowerL2": 0.376,
        "instantaneousProducedPowerL3": 0.634,
        "instantaneousVoltageL1": 233.1,
        "instantaneousVoltageL2": 231.8,
        "instantaneousVoltageL3": 235.2,
        "instantaneousCurrentL1": 0.76,
        "instantaneousCurrentL2": 1.78,
        "instantaneousCurrentL3": 3.03,
        "switchPosition": 1,
        "thresholdkW": 999.9,
        "equipmentId": "1SAG3100185546"
    },
    "gas": {},
    "water": {},
    "meterModel": "FLU5\\253769484_A",
    "dsmrVersion": 5.0217,
    "timestamp": 1675675314,
    "messages": {
        "text": ""
    }
}
```

The runningMonth timestamp is 1675267200 which is the epoch for Wednesday 1 February 2023 17:00:00 CET, which is what is in the telegram 230201170000W (23=2023, 02=feb, 01=feb 1, 17:00:00, W=winter time).

The first historic report start is 1672527600 (Sunday 1 Januari 2023 00:00:00 CET) and end is 1669995900 (Friday 1 December 2 2022 16:45 CET) which correspond with 230101000000W and 221202164500W.
The second historic report start is 1675206000 (Wednesday 1 februari 2023 00:00:00 CET) and end is 1674662400 (Wednesday 25 januari 2023 17:00:00 CET) which correspond with 230201000000W and 230125170000W.

What is wrong is that I parsed the end as the start and vice versa, I will fix this, but the timestamps are what is in the telegram.

**Comment by Henkkas52** [comment]
Yes, I see my mistake now. I interpreted the timestamp as msec, not as seconds as I should have. 

I might be wrong here, but I think the 2 dates that are mentioned in historic per period, is one is end of period and 2 is peak-moment.

The consequence for me is, that my capacity sealing for December 2022 is determined at 2772 Watts, and for January this year on 2600 Watts. They are both a little bit over the standard of 2500 watts, so they will raise for those months the transport cost for me by a certain percentage.
