### ISSUE TITLE
Connected but not getting telegrams

### ISSUE THREAD

**Issue by ghost** [reneklootwijk/node-dsmr#4]
When I manually open the serial connection I can see the telegrams:

```
# sudo cu -l /dev/ttyUSB0 -s 9600 -e -E q
Connected.
/ISk5\2MT382-1004

0-0:96.1.1(5A424556303035313832323533303133)
1-0:1.8.1(12500.539*kWh)
1-0:1.8.2(13054.067*kWh)
1-0:2.8.1(00000.000*kWh)
1-0:2.8.2(00000.002*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(0000.50*kW)
1-0:2.7.0(0000.00*kW)
0-0:17.0.0(0999.00*kW)
0-0:96.3.10(1)
0-0:96.13.1()
0-0:96.13.0()
0-1:24.1.0(3)
0-1:96.1.0(4730303135353631313037313331333133)
0-1:24.3.0(200410180000)(00)(60)(1)(0-1:24.2.1)(m3)
(05780.901)
0-1:24.4.0(1)
!
/ISk5\2MT382-1004
```

The following also works:
`sudo screen /dev/ttySUSB0 9600,cs7`

When I run the following test script I only get "Connected" as the output:

```javascript
const SmartMeter = require('node-dsmr')

var options = {
    port: '/dev/ttyUSB0',
    baudrate: 9600,
    bits: 7,
    parity: 'even'
}

var smartMeter = new SmartMeter(options)

smartMeter.connect()


smartMeter.on('connected', () => {
console.log('Connected')
})

smartMeter.on('telegram', telegram => {
console.log(telegram)
})
```

**Comment by Fossil01** [comment]
Turns out I was running Node 8, tried updating to 12 but when I run the same code now it doesn't even connect :-(

Ideas?

**Comment by ghost** [comment]
Did some more debugging. Changed log level to debug:

{"message":"Connection.connect: Entering","level":"debug"}
{"message":"Connected using serial connection","level":"debug"}

And then added a logger.debug line in connection.js:

```javascript
    parser.on('data', function (data) {
      logger.debug(data)
      self.emit('data', data)
    })
```

This now outputs some data to the screen:
```
{"message":"\u0000��r����M�&�-ln&[L���j��9��l)C�\u0005���M����0�ӊ3�&�����3&�S�ߥ��l\t��.�.l�6�\u0013���3N�c��\t��.���Jl&�\u0013s�9&m��jL<ׂ��.��lo&7\u0013���0�ս\u001d/k","level":"debug"}
{"message":"l\t��.��6\t���0���6m��jL\fj��9��l�\tB��0�jL<k�鱿�\tB��0����m�jL<k�鲿�\tB��0���L��k","level":"debug"}
{"message":"�Kn���\trá0N�'\t���]��\u0004j��9��&)��ũc!�\t���.l&)C�Kn����3���jL\fj�:��)sá3jL\fj�:N�)sá��\u000e��ͱ�Ӫ��3l��\u0013��3l��S��ͱ����\u0004j�:��irá�0��l��0jo&�\r�å(l%�)�۴��)K({���ݸ0�N\u001bJ���K~'?��sá�jL<j","level":"debug"}
```

So it seems that data isn't further processed by this package for some reason?

[EDIT]
It seems it fails because the variable "full" is never truthy. Possibly because it cannot find the exclamation mark in the response because of the gibberish response?

**Comment by ghost** [comment]
Ok figured it out lol. the options object contains "bits" which should be "databits"

**Comment by reneklootwijk** [comment]
Thanks for reporting, I fixed the documentation.
